os: linux
dist: bionic
language: python
python: 3.7

services:
  - docker

branches:
  only:
    - master
    - dev
    - /^\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: Run tests
      name: QGIS and PostGIS
      install:
        - cd .docker
        - ./start.sh with-qgis
      script:
        - ./exec.sh

#    - stage: Run tests
#      name: Database installation versus running migrations
#      install:
#        - cd .docker
#        - ./start.sh
#      script:
#        - ./install_migrate_generate.sh

#    - stage: Translations
#      name: Push translations
#      if: branch = master AND type != pull_request
#      install:
#        - pip3 install qgis-plugin-ci==1.8.4
#      script: qgis-plugin-ci push-translation ${TX_TOKEN}

    - stage: Deploy
      if: tag IS present
      name: Create release, plugins.qgis.org
      install:
        - pip3 install qgis-plugin-ci==1.8.4
      before_deploy:
        - export RELEASE_TITLE=${TRAVIS_TAG}
        - qgis-plugin-ci changelog $TRAVIS_TAG > ../release.md
        - cat ../release.md
      script:
        - qgis-plugin-ci -v
      deploy:
        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          release_notes_file: ../release.md
          token: ${GH_TOKEN}
          on:
            tags: true

        - provider: script
          script: >-
            qgis-plugin-ci
            release ${TRAVIS_TAG}
            --github-token ${GH_TOKEN}
            --create-plugin-repo
            --allow-uncommitted-changes
          on:
            tags: true

        - provider: script
          script: .github/push_translations_to_github.sh
          on:
            tags: true
