version: '3.9'

networks:
  qgis_plugin_network:

services:
  db:
    profiles:
      - "qgis"
      - "db"
    image: kartoza/postgis:11.5-2.5  # Despite the tag, it's a 11.7 version
    container_name: postgis
    networks:
      qgis_plugin_network:
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=gis
      # Uncomment to expose the postgis database on the network
      # - ALLOW_IP_RANGE= 0.0.0.0/0
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_raster
    volumes:
      - ../${PLUGIN_NAME}:/tests_directory/${PLUGIN_NAME}
    # Uncomment to use the postgis database from outside the docker network
    ports:
      - "35432:5432"
    # Only supported in version 3
    # But we need version 2 for extends
    #healthcheck:
    #  test: "exit 0"

  qgis:
    profiles:
      - "qgis"
    image: qgis/qgis:release-3_16
    container_name: qgis
    networks:
      qgis_plugin_network:
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ../${PLUGIN_NAME}:/tests_directory/${PLUGIN_NAME}
    environment:
      # - DISPLAY=unix$DISPLAY
      - DISPLAY=:99
