name: Release

on:
  push:
    tags:
      - '*'

jobs:
  zipping:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install qgis-plugin-ci
      run: pip3 install qgis-plugin-ci==1.8.4

    - name : Get current changelog
      run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_HUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: release.md

    - name: Deploy plugin
      run: >-
        qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --github-token ${{ secrets.BOT_HUB_TOKEN }}
        --create-plugin-repo
