name: Migration 🗂

on:
  push:
#    paths:
#      - '**.sql'
  pull_request:
#    paths:
#      - '**.sql'

jobs:
  test-migration:
    name: "Migration"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launching docker-compose
        run: ./start.sh
      - name: Running tests
        run: ./install_migrate_generate.sh
